services:
  - type: web
    name: todo-backend
    env: python
    plan: free
    runtime: python3.12
    regions:
      - oregon
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    releaseCommand: alembic upgrade head
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    disk: 1024
