import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DarkModeToggle from '@/components/DarkModeToggle'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <header className="py-6">
          <div className="app-container">
            <div className="flex items-center justify-between">
                <div>
                  <h1 className="text-2xl font-semibold">Todo App</h1>
                  <p className="text-sm subtitle">A little fancier — created with ❤️</p>
                </div>
                <div>
                  <DarkModeToggle />
                </div>
              </div>
          </div>
        </header>
        <main className="app-container flex-1">{children}</main>
        <footer className="app-container py-8 text-center muted text-sm">
          Made with care — try adding a task ✨
        </footer>
      </body>
    </html>
  );
}
