"""Add advanced features: tags, due_date, subtasks

Revision ID: c9a819ab9109
Revises: 
Create Date: 2026-03-16 21:55:55.708837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a819ab9109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False, unique=True),
        sa.Column('color', sa.String(length=7), nullable=False, server_default='#3B82F6'),
    )

    op.create_table(
        'todos',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.text('0')),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.Column('parent_id', sa.Integer(), sa.ForeignKey('todos.id'), nullable=True),
    )

    op.create_table(
        'todo_tags',
        sa.Column('todo_id', sa.Integer(), sa.ForeignKey('todos.id'), primary_key=True, nullable=False),
        sa.Column('tag_id', sa.Integer(), sa.ForeignKey('tags.id'), primary_key=True, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_tags')
    op.drop_table('todos')
    op.drop_table('tags')
    # ### end Alembic commands ###